apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeapp
  template:
    metadata:
      labels:
        app: kubeapp
    spec:
      containers:
      - name: kubeapp
        image: <your-dockerhub-username>/kubeapp:latest
        ports:
        - containerPort: 8090
